apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: 01-bgp-peering-policy
spec:
 nodeSelector:
   matchLabels:
     kubernetes.io/hostname: clab-bgp-cplane-control-plane
 virtualRouters:
 - localASN: 65225
   exportPodCIDR: false
   neighbors:
    - peerAddress: '192.168.97.254/32'
      peerASN: 65531
      connectRetryTimeSeconds: 12
      holdTimeSeconds: 9
      keepAliveTimeSeconds: 3
      eBGPMultihopTTL: 3
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 20
   serviceSelector:
     matchExpressions:
       - {key: somekey, operator: NotIn, values: ['never-used-value']}
